name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Mod Jar
      run: ./gradlew jar
    - name: Display Files
      run: ls build/libs/
