name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Mod Jar
      run: ./gradlew jar
    - name: Display Files
      run: ls build/libs/
    - name: Send Jar To Releases
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "build/libs/${{ github.event.repository.name }}-desktop.jar"
        overwrite: true
