name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
    - name: Build plugin jar
      run: ./gradlew jar
    - name: Upload built jar file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: out/${{ github.event.repository.name }}.jar
