name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Mod Jar
      run: ./gradlew jar
    - name: Display Files
      run: ls build/libs/
    - name: Retrieve Version
      run: echo "::set-output name=VERSION_NAME::$(./gradlew -q printVersion)"
      id: mod_version
    - name: Get version
      run: echo "version_name=${{steps.mod_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
    - name: Send Jar To Releases
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "build/libs/${{ github.event.repository.name }}-desktop-${{env.version_name}}.jar"
        overwrite: true
        tag_name: "${{ github.event.repository.name }}-${{env.version_name}}"
        draft: false
